# Generated by Django 3.2.9 on 2021-12-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.FileField(blank=True, upload_to='')),
                ('result', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
